version: '3'

volumes:
  jenkins-data:
  jenkins-log:

networks:
  jenkins-net:

services:
  master:
    build: ./jenkins-master
    container_name: jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    build: ./jenkins-nginx
    container_name: jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave:
    build: ./jenkins-slave
  proxy:
    # build: ./docker-proxy
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1
